# Generated by Django 4.2.1 on 2023-05-04 14:07

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    def create_super_user(apps, schema_editor):
        if settings.DEBUG:
            User = apps.get_model("users", "User")
            user = User.objects.create(
                username="useradmin",
                is_superuser=True,
                is_staff=True,
                email="admin@admin.com",
            )
            user.password = make_password("admin123123")
            user.save()

            Profile = apps.get_model("users", "Profile")

            Profile.objects.create(user=user)

            EmailAddress = apps.all_models.get("account").get("emailaddress")
            EmailAddress.objects.create(
                user=user, email=user.email, verified=True, primary=True
            )

    operations = [
        migrations.RunPython(create_super_user),
    ]
