# Generated by Django 5.2.2 on 2025-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20230504_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_test_user",
            field=models.BooleanField(default=False),
        ),
    ]
