# Generated by Django 4.2.1 on 2023-10-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_unique_username_user_unique_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenrecovery",
            name="token",
            field=models.CharField(default="", max_length=25),
        ),
    ]
