services:
  web:
    build:
      context: .
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
