#!/bin/bash

# Define tu nombre de contenedor Docker
DOCKER_CONTAINER_NAME="web"

# Ejecuta los tests de Django dentro del contenedor Docker
TEST_RESULT=$(docker compose exec -it $DOCKER_CONTAINER_NAME python3 manage.py test 2>&1)

# Verifica si hay un error en la respuesta del demonio de Docker
if echo "$TEST_RESULT" | grep -q "Error response from daemon: No such container"; then
    echo "Error: No se encontró el contenedor Docker '$DOCKER_CONTAINER_NAME'."
    exit 1
fi

# Verifica si hay fallos en los resultados de los tests
if echo "$TEST_RESULT" | grep -q "FAILED"; then
    echo "$TEST_RESULT"
    echo "Advertencia: Algunos tests han fallado."

    # Pregunta al usuario si quiere continuar con el push
    read -p "¿Quieres continuar con el push a pesar de los fallos en los tests? (y/n): " -n 1 -r
    echo  # Agrega una nueva línea después de la entrada del usuario

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Push abortado debido a los fallos en los tests."
        exit 1
    fi

    echo "Continuando con el push a pesar de los fallos en los tests..."
fi

echo "Procediendo con el push..."
exit 0
