# Generated by Django 5.0.7 on 2024-07-30 13:42

from django.db import migrations


def create_obj(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SystemStatus = apps.get_model("django_base", "SystemStatus")
    SystemStatus.objects.using(db_alias).create()


class Migration(migrations.Migration):
    dependencies = [
        ("django_base", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_obj),
    ]
