name: Deploy to Amazon ECS - Main #TODO: Upgrade file with Hiring one.

on:
  push:
    branches: [ "main" ] #main/develop/others 

env:
  AWS_REGION: us-east-1
  
  ENVIRONMENT: production

  ECR_REPOSITORY: <project_name>-backend-ECR-production
  ECS_CLUSTER: <project_name>-backend-cluster-production
  ECS_SERVICE: <project_name>-backend-service-production
  TASK_DEFINITION_FAMILY: <project_name>-backend-task-production
  CONTAINER_NAME: <project_name>-backend-container-production

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Cache Docker layers
      id: cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker buildx build --push -t $ECR_REGISTRY/$ECR_REPOSITORY \
          --cache-to type=local,dest=/tmp/.buildx-cache \
          --cache-from type=local,src=/tmp/.buildx-cache .
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY" >> $GITHUB_OUTPUT

    - name: Download task definition
      env:
        TASK_DEFINITION_FAMILY: ${{ env.TASK_DEFINITION_FAMILY }}
      run: |
        aws ecs describe-task-definition --task-definition $TASK_DEFINITION_FAMILY --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        details: Deploy Failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
