# Generated by Django 5.0.7 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="Is operational"),
                ),
            ],
            options={
                "verbose_name": "System Status",
                "verbose_name_plural": "System Status",
            },
        ),
    ]
