# Generated by Django 4.2.1 on 2023-10-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("platform_configurations", "0002_country_json_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=3)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="platform_configurations.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "States",
            },
        ),
    ]
