# Generated by Django 4.2.1 on 2023-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_configurations", "0003_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
