# Generated by Django 4.2.1 on 2023-10-30 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("platform_configurations", "0004_alter_state_latitude_alter_state_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="json_id",
        ),
    ]
